### ISSUE TITLE
Is thread safe ?

### ISSUE THREAD

**Issue by berli** [rxi/log.c#1]
Is thread safe ?
can it use in multi threads ?

**Comment by rxi** [comment]
You'll need to provide a lock using [`log_set_lock()`](https://github.com/rxi/log.c#log_set_locklog_lockfn-fn) if you'll be calling the library's functions from multiple threads.

**Comment by msaiducar** [comment]
Can you give an example to setting lock using log_set_lock() function?

**Comment by rxi** [comment]
Here's an example using a mutex provided by the SDL2 library:

```c
#include <SDL2/SDL.h>
#include "log.h"


static void lock_callback(void *udata, int lock) {
  if (lock) {
    SDL_LockMutex(udata);
  } else {
    SDL_UnlockMutex(udata);
  }
}


int main(void) {
  SDL_mutex *mutex = SDL_CreateMutex();

  log_set_udata(mutex);
  log_set_lock(lock_callback);

  log_trace("hello world");

  SDL_DestroyMutex(mutex);
  return EXIT_SUCCESS;
}
```
