### ISSUE TITLE
Why keep multiple callbacks

### ISSUE THREAD

**Issue by kevin-tso** [rxi/log.c#30]
https://github.com/rxi/log.c/blob/f9ea34994bd58ed342d2245cd4110bb5c6790153/src/log.c#L38

**Comment by CyfTX** [comment]
Using different callback functions can display different log styles

**Comment by kevin-tso** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by kevin-tso** [comment]
thank you
